/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DtrInternRouteImport } from './routes/dtr/intern'
import { Route as DtrEmployeeRouteImport } from './routes/dtr/employee'

const DtrInternRoute = DtrInternRouteImport.update({
  id: '/dtr/intern',
  path: '/dtr/intern',
  getParentRoute: () => rootRouteImport,
} as any)
const DtrEmployeeRoute = DtrEmployeeRouteImport.update({
  id: '/dtr/employee',
  path: '/dtr/employee',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dtr/employee': typeof DtrEmployeeRoute
  '/dtr/intern': typeof DtrInternRoute
}
export interface FileRoutesByTo {
  '/dtr/employee': typeof DtrEmployeeRoute
  '/dtr/intern': typeof DtrInternRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dtr/employee': typeof DtrEmployeeRoute
  '/dtr/intern': typeof DtrInternRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dtr/employee' | '/dtr/intern'
  fileRoutesByTo: FileRoutesByTo
  to: '/dtr/employee' | '/dtr/intern'
  id: '__root__' | '/dtr/employee' | '/dtr/intern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DtrEmployeeRoute: typeof DtrEmployeeRoute
  DtrInternRoute: typeof DtrInternRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dtr/intern': {
      id: '/dtr/intern'
      path: '/dtr/intern'
      fullPath: '/dtr/intern'
      preLoaderRoute: typeof DtrInternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtr/employee': {
      id: '/dtr/employee'
      path: '/dtr/employee'
      fullPath: '/dtr/employee'
      preLoaderRoute: typeof DtrEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DtrEmployeeRoute: DtrEmployeeRoute,
  DtrInternRoute: DtrInternRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
