/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutPublicRouteImport } from './routes/_layout/_public'
import { Route as LayoutPrivateRouteImport } from './routes/_layout/_private'
import { Route as LayoutPublicRegisterRouteImport } from './routes/_layout/_public/register'
import { Route as LayoutPublicLoginRouteImport } from './routes/_layout/_public/login'
import { Route as LayoutPrivateDtrInternRouteImport } from './routes/_layout/_private/dtr/intern'
import { Route as LayoutPrivateDtrEmployeeRouteImport } from './routes/_layout/_private/dtr/employee'

const LayoutPublicRoute = LayoutPublicRouteImport.update({
  id: '/_layout/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPrivateRoute = LayoutPrivateRouteImport.update({
  id: '/_layout/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPublicRegisterRoute = LayoutPublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicLoginRoute = LayoutPublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPrivateDtrInternRoute = LayoutPrivateDtrInternRouteImport.update({
  id: '/dtr/intern',
  path: '/dtr/intern',
  getParentRoute: () => LayoutPrivateRoute,
} as any)
const LayoutPrivateDtrEmployeeRoute =
  LayoutPrivateDtrEmployeeRouteImport.update({
    id: '/dtr/employee',
    path: '/dtr/employee',
    getParentRoute: () => LayoutPrivateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutPublicRouteWithChildren
  '/login': typeof LayoutPublicLoginRoute
  '/register': typeof LayoutPublicRegisterRoute
  '/dtr/employee': typeof LayoutPrivateDtrEmployeeRoute
  '/dtr/intern': typeof LayoutPrivateDtrInternRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutPublicRouteWithChildren
  '/login': typeof LayoutPublicLoginRoute
  '/register': typeof LayoutPublicRegisterRoute
  '/dtr/employee': typeof LayoutPrivateDtrEmployeeRoute
  '/dtr/intern': typeof LayoutPrivateDtrInternRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout/_private': typeof LayoutPrivateRouteWithChildren
  '/_layout/_public': typeof LayoutPublicRouteWithChildren
  '/_layout/_public/login': typeof LayoutPublicLoginRoute
  '/_layout/_public/register': typeof LayoutPublicRegisterRoute
  '/_layout/_private/dtr/employee': typeof LayoutPrivateDtrEmployeeRoute
  '/_layout/_private/dtr/intern': typeof LayoutPrivateDtrInternRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/dtr/employee' | '/dtr/intern'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/dtr/employee' | '/dtr/intern'
  id:
    | '__root__'
    | '/_layout/_private'
    | '/_layout/_public'
    | '/_layout/_public/login'
    | '/_layout/_public/register'
    | '/_layout/_private/dtr/employee'
    | '/_layout/_private/dtr/intern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutPrivateRoute: typeof LayoutPrivateRouteWithChildren
  LayoutPublicRoute: typeof LayoutPublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout/_public': {
      id: '/_layout/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_private': {
      id: '/_layout/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_public/register': {
      id: '/_layout/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoutPublicRegisterRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/login': {
      id: '/_layout/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutPublicLoginRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_private/dtr/intern': {
      id: '/_layout/_private/dtr/intern'
      path: '/dtr/intern'
      fullPath: '/dtr/intern'
      preLoaderRoute: typeof LayoutPrivateDtrInternRouteImport
      parentRoute: typeof LayoutPrivateRoute
    }
    '/_layout/_private/dtr/employee': {
      id: '/_layout/_private/dtr/employee'
      path: '/dtr/employee'
      fullPath: '/dtr/employee'
      preLoaderRoute: typeof LayoutPrivateDtrEmployeeRouteImport
      parentRoute: typeof LayoutPrivateRoute
    }
  }
}

interface LayoutPrivateRouteChildren {
  LayoutPrivateDtrEmployeeRoute: typeof LayoutPrivateDtrEmployeeRoute
  LayoutPrivateDtrInternRoute: typeof LayoutPrivateDtrInternRoute
}

const LayoutPrivateRouteChildren: LayoutPrivateRouteChildren = {
  LayoutPrivateDtrEmployeeRoute: LayoutPrivateDtrEmployeeRoute,
  LayoutPrivateDtrInternRoute: LayoutPrivateDtrInternRoute,
}

const LayoutPrivateRouteWithChildren = LayoutPrivateRoute._addFileChildren(
  LayoutPrivateRouteChildren,
)

interface LayoutPublicRouteChildren {
  LayoutPublicLoginRoute: typeof LayoutPublicLoginRoute
  LayoutPublicRegisterRoute: typeof LayoutPublicRegisterRoute
}

const LayoutPublicRouteChildren: LayoutPublicRouteChildren = {
  LayoutPublicLoginRoute: LayoutPublicLoginRoute,
  LayoutPublicRegisterRoute: LayoutPublicRegisterRoute,
}

const LayoutPublicRouteWithChildren = LayoutPublicRoute._addFileChildren(
  LayoutPublicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutPrivateRoute: LayoutPrivateRouteWithChildren,
  LayoutPublicRoute: LayoutPublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
